#!/usr/bin/env bash

echo "Generating ssh key pair if not exists ..."
  [[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa

echo "Installing homebrew, OS X package manager ..."
  /usr/bin/ruby -e "$(/usr/bin/curl -fsSL https://raw.github.com/mxcl/homebrew/master/Library/Contributions/install_homebrew.rb)"
  brew update

echo "Installing zsh, a powerful extension of bash ..."
  brew install zsh

echo "Installing oh-my-zsh, a community-driven framework for managing your zsh configuration ..."
  wget --no-check-certificate https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | sh

echo "Put Homebrew location earlier in PATH ..."
  echo "
# recommended by brew doctor
export PATH='/usr/local/bin:$PATH'" >> ~/.zshrc
  source ~/.zshrc

echo "Installing ack, grep-like tool optimized for source code searching ..."
  brew install ack

echo "Installing MacVim, a GUI version of vim ..."
  brew install macvim

echo "Configurating MacVim using janus' vim bootstrapping script ..."
  curl https://raw.github.com/carlhuda/janus/master/bootstrap.sh -o - | sh

echo "Installing tmux, a terminal multiplexer ..."
  brew install tmux
